services:
  qgis-server:
    image: qgis/qgis-server:ltr
    container_name: qgis-server
    volumes:
     # Data should be mount RO when working
     # with GeoPackages and more than one QGIS container
     - ./data:/io/data:ro
     # - ./plugins:/io/plugins
     # - ./fonts:/usr/share/fonts
     # - ./svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg
     # Connection Parameters for a PostgreSQL database
     # - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
    environment:
      # Do not run the embedded copy of nginx
      # SKIP_NGINX: true
      # Serve this project only / by default
      QGIS_PROJECT_FILE: /io/data/world/world.qgs
      QGIS_SERVER_LOG_LEVEL: 0
      # Adjust based on available server capacities
      MAX_CACHE_LAYERS: 100
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
    restart: unless-stopped
    ports:
      - 80:80

